### ISSUE TITLE
Provide binaries for download

### ISSUE THREAD

**Issue by probonopd** [Skyus/Malice#1]
Please provide binaries for download on the GitHub Releases page.

**Comment by donn** [comment]
I will! I'm just waiting until I can download older versions of Ubuntu so I can compile them there, as AppImages are forwards compatible but not backwards compatible.

(I am currently on limited data.)

**Comment by probonopd** [comment]
You could also use a service like [Travis CI](https://travis-ci.org/) where the builds run in the cloud.

**Comment by donn** [comment]
Honestly hadn't crossed my mind. I'll look into it.

**Comment by donn** [comment]
I set up the automated build. Thanks for the suggestion (and for AppImage)!
